name: CICD

on: 
  push:
    branches: [ main ]

jobs:
  BUILD:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: BUILD the application
      run: echo "APPLICATION IS BUILDING!"
  
  TEST:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: TEST the application
      run: echo "APPLICATION IS TESTING!"

  DEPLOY-TO-STAGE:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: STAGING Deployment
      run: echo "staging deployment!!"
  


